name: Build
on:
  push:
    branches:
      -master
jobs:
  build:
    name: Build and Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:[windows-latest,ubuntu-latest]
    steps:
      - name: Baixa os arquivos fonte
        uses: actions/checkout@v1
      - name: Instala as dependências
        run: npm ci
      - name: Build
        run: npm run all
